[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
hook_source = 'source ~/.config/nvim/rc/plugins_lazy/denite.rc.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-fugitive.git'
on_cmd = 'Git'
hook_add = '''
  let g:airline#extensions#branch#enabled = 1
  nnoremap [fugitive]  <Nop>
  nmap <leader>g [fugitive]
  nnoremap <silent> [fugitive]s :Git<CR>
'''
