[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  syntax on
  colorscheme iceberg
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes.git'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0

# [[plugins]]
# repo = 'leafgarland/typescript-vim'
# on_ft = ['typescript', 'typescriptreact']

 #[[plugins]]
# repo = 'maxmellon/vim-jsx-pretty'
# on_ft = ['javascriptreact', 'typescriptreact']
