cask_args appdir: '/Applications'

tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew 'zsh'
brew 'zplug'
brew 'peco'
brew 'tmux'
brew 'neovim'
brew 'tig'
brew 'ghq'
brew 'fontforge'
brew 'python'
brew 'python@2'

cask 'font-source-han-code-jp'
cask "google-chrome"
cask "google-japanese-ime"
cask "microsoft-office"
cask "kindle"
cask "chatwork"
cask "zoomus"
cask "skype"
cask "adobe-creative-cloud"
cask "iterm2"
cask "docker"
cask "parallels"

mas "1Password 7 - Password Manager", id: 1333542190
mas "Slack", id: 803453959
mas "CotEditor", id: 1024640650
